import Head from 'next/head'
import styles from '../styles/Home.module.css'
import client from '../client'
import groq from 'groq'
import Link from 'next/link'

const Home = ({post}) => {
  const {work = []} = post

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hi, My name is koray</h1>

        {work &&
          work.length > 0 &&
          work.map(
            ({_id, title = '', slug = '', _updatedAt = ''}) =>
              slug && (
                <li key={_id}>
                  <Link href={`/work/[slug]`} as={`/work/${slug.current}`}>
                    <a>{title}</a>
                  </Link>{' '}
                  ({new Date(_updatedAt).toDateString()})
                </li>
              )
          )}
      </main>

      <footer className={styles.footer} />
    </div>
  )
}

export async function getStaticProps() {
  let post = await client.fetch(groq`
      {"work": *[_type == "work"]|order(publishedAt desc)}
    `)

  return {
    props: {
      post
    }
  }
}

export default Home
